---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: michaeltay
resources:
  - config-map.yaml
  - deployment-mlapi.yaml
  - deployment-redis.yaml
  - service-mlapi.yaml
  - service-redis.yaml
