---
apiVersion: v1
kind: Service
metadata:
  name: mlapi
  labels:
    app: mlapi
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: mlapi
