apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlapi
  namespace: michaeltay
  labels:
    app: mlapi
spec:
  replicas: 1 # Set this to 1 due to memory limits for local dev
  selector:
    matchLabels:
      app: mlapi
  template:
    metadata:
      labels:
        app: mlapi
    spec:
      containers:
      - name: mlapi
        image: project:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: 2000Mi
          limits:
            memory: 2000Mi
        ports:
        - containerPort: 8000
        startupProbe:
         httpGet:
            path: /health
            port: 8000
         failureThreshold: 1
         initialDelaySeconds: 30
         periodSeconds: 2
        readinessProbe:
         initialDelaySeconds: 1
         periodSeconds: 2
         timeoutSeconds: 1
         successThreshold: 1
         failureThreshold: 1
         httpGet:
            host:
            scheme: HTTP
            path: /health
            port: 8000
         initialDelaySeconds: 5
         periodSeconds: 5        
        livenessProbe:
         httpGet:
            path: /health
            port: 8000
         failureThreshold: 1
         periodSeconds: 60
         terminationGracePeriodSeconds: 60
      initContainers:
        - name: init-verify-redis-dns
          image: busybox:1.28
          imagePullPolicy: Always
          command:
            [
              "sh",
              "-c",
              "until nc -vz redis-service 6379; do echo 'waiting for redis service from DNS'; sleep 2; done",
            ]
        - name: init-verify-redis-ready
          image: busybox:1.28
          imagePullPolicy: Always
          command:
            [
              "sh",
              "-c",
              "until (printf 'PING\r\n';) | nc redis-service 6379; do echo 'waiting for redis to PONG'; sleep 1; done",
            ]

